### ISSUE TITLE
activate script doesn't work if there's no PS1 and the shell is `set -e`

### ISSUE THREAD

**Issue by chriskuehl** [chriskuehl/rustenv#1]
This happens e.g. in bash scripts (as opposed to logged-in sessions).

```
$ cat test.sh
#!/bin/bash
set -euo pipefail
. renv/bin/activate

$ ./test.sh  
renv/bin/activate: line 6: PS1: unbound variable
```

It should probably skip setting the PS1 in this case entirely?

**Comment by asottile** [comment]
those seem unrelated -- and I don't think rustenv should read virtualenv's environment variables -- but feel free to work on fixing this bug at least
