### ISSUE TITLE
readlink issues on Mac OS

### ISSUE THREAD

**Issue by fortizc** [chriskuehl/rustenv#4]
The script called `rustenv-proxy` use `readlink -f` but in Mac OS uses BSD like commands and this option is not supported. It seems that the easiest fix is to remove `rustenv-proxy` and create links for each rust binary. Is there any reason to use `rustenv-proxy`?

**Comment by asottile** [comment]
It should be pretty easy to replace `readlink -f` with `cd -L && pwd` if you're willing to submit a patch 👍

**Comment by chriskuehl** [comment]
There's a comment in the code that explains why just using symlinks unfortunately won't work:
https://github.com/chriskuehl/rustenv/blob/8e733b1e43a4add66d979156e7a41c08c8d36b2b/rustenv.py#L92-L108

Would definitely be open to changing the shims to work on OS X, though (or any other solution, if there's a better one than shims?).

(To be clear, the shims are only needed for the `cargo`, `rustc`, etc. binaries that get provided by rustup -- not actually all Rust-built binaries.)

**Comment by josephcomisi** [comment]
Any fix on this issue ?

**Comment by josephcomisi** [comment]
What about `rustinstall=$(dirname $(dirname "$0"))/rust` ?

**Comment by josephcomisi** [comment]
On a fresh install (with readlink):

renv/bin/rustc --version
readlink: illegal option -- f
usage: readlink [-n] [file ...]
usage: dirname path
usage: dirname path

With _cd -L && pwd_ in place of _readlink -f_:

renv/bin/rustc --version
renv/bin/rustc: line 6: //rust/bin/rustc: No such file or directory

With _rustinstall=$(dirname $(dirname "$0"))/rust_ :

renv/bin/rustc --version
rustc 1.46.0 (04488afe3 2020-08-24)

**Comment by asottile** [comment]
🤦 this is why you show what you're doing instead of just saying "it doesn't work" (and don't just blindly copy paste code from the internet!), it should be `$(cd -L "$(dirname 0)" && pwd)"`

**Comment by josephcomisi** [comment]
Please be more clear in your instructions. What is the your full rustinstall?

**Comment by asottile** [comment]
I'm sorry, I assumed I wouldn't have to explain what `cd` does or `pwd` since they're 101-level unix commands

**Comment by asottile** [comment]
or that the implementer would google "readlink -f on macos"

**Comment by josephcomisi** [comment]
> I'm sorry, I assumed I wouldn't have to explain what cd does or pwd since they're 101-level unix commands

Never did that. Please, could you just provide your solution so I can test it and we can move forward ?

**Comment by garethhowell** [comment]
My solution was to replace `readlink -f` with `realpath`, so
```
rustinstall=$(dirname $(dirname $(realpath "$0")))/rust
```

**Comment by cblegare** [comment]
> It should be pretty easy to replace `readlink -f` with `cd -L && pwd` if you're willing to submit a patch

@asottile A patch have been submitted ;) #5
